/**
 * Scene Analyzer Service
 *
 * Uses Gemini 2.5 Flash to forensically segment a video into individual scenes
 * with precise timestamps, scene types, and detailed descriptions. This is the
 * foundation for video cloning with product swaps — it identifies:
 *
 * - TALKING_HEAD scenes (person speaking to camera)
 * - BROLL scenes (cutaway footage, transitions, establishing shots)
 * - PRODUCT_SHOT scenes (product close-ups, demos, unboxing)
 * - TRANSITION scenes (motion graphics, text cards, wipes)
 *
 * Each scene includes enough detail for downstream services to regenerate it
 * with different products/avatars while preserving the original video's DNA.
 */

import { GoogleGenAI } from "@google/genai";
import { getGeminiKey } from "../lib/keys";
import { parseLlmJson } from "../lib/parse-llm-json";
import { resolveVideoUrl } from "./video-url-resolver";
import * as fs from "fs";
import * as path from "path";

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type SceneType = "talking_head" | "broll" | "product_shot" | "transition";

export interface DetectedProduct {
  name: string;
  description: string;
  position: string; // e.g., "held in right hand", "on counter left side"
  visibleFeatures: string; // color, shape, packaging type
  interactionType: string; // "held", "placed", "being applied", "opened", etc.
}

export interface SceneSegment {
  index: number;
  type: SceneType;
  startSeconds: number;
  endSeconds: number;
  durationSeconds: number;
  description: string; // Dense visual description of the scene
  cameraWork: string; // Camera angle, movement, shot type
  lighting: string; // Lighting conditions
  environment: string; // Setting/background
  subject: string; // Who/what is in the scene
  dialogue: string; // Spoken words in this segment (empty for B-roll)
  products: DetectedProduct[]; // Products visible in this scene
  motionDescription: string; // Physical movements/actions happening
  colorPalette: string; // Dominant colors
  energy: string; // low/medium/high
  isSwappable: boolean; // Can this scene's product be swapped?
  swapDifficulty: "easy" | "medium" | "hard"; // How hard to swap the product
  swapNotes: string; // Guidance for product swap
}

export interface SceneAnalysisResult {
  totalDuration: number;
  aspectRatio: "9:16" | "16:9" | "1:1";
  sceneCount: number;
  scenes: SceneSegment[];
  overallStyle: string; // Summary of the video's visual DNA
  speakerProfile: string; // Description of the main speaker
  productSummary: string; // Summary of all products detected
  scriptFull: string; // Full transcription
  hookStrategy: string; // How the video grabs attention
  targetPlatform: string; // TikTok, Instagram, YouTube Shorts
  resolvedVideoUrl?: string; // Direct download URL (set when social media URL is resolved)
}

// ─────────────────────────────────────────────
// Gemini Scene Analysis Prompt
// ─────────────────────────────────────────────

const SCENE_ANALYSIS_PROMPT = `You are an elite video forensic analyst specializing in scene segmentation for AI video cloning. Your job is to deconstruct a video into individual SCENES with precise timestamps, so each scene can be independently regenerated by an AI video model.

CRITICAL: You must output VALID JSON and nothing else. No markdown, no code fences, no explanation.

Analyze the video and produce a JSON object with this exact schema:

{
  "totalDuration": <number, total video duration in seconds>,
  "aspectRatio": "<9:16 | 16:9 | 1:1>",
  "sceneCount": <number>,
  "scenes": [
    {
      "index": <0-based>,
      "type": "<talking_head | broll | product_shot | transition>",
      "startSeconds": <number, precise start time>,
      "endSeconds": <number, precise end time>,
      "durationSeconds": <number>,
      "description": "<Dense 2-3 sentence visual description of exactly what happens in this scene. Include camera angle, subject position, background, action.>",
      "cameraWork": "<Shot type (close-up/medium/wide), camera angle (eye-level/low/high), movement (static/pan/tracking/handheld), lens feel>",
      "lighting": "<Light source type, direction, quality, color temperature, shadows>",
      "environment": "<Setting, background elements, surfaces, props>",
      "subject": "<Who/what is in frame, their appearance, clothing, position>",
      "dialogue": "<Exact spoken words in this segment, empty string if none>",
      "products": [
        {
          "name": "<Product name if visible/mentioned, or 'unknown product'>",
          "description": "<Physical description: color, shape, size, packaging>",
          "position": "<Where in frame: held in hand, on counter, etc.>",
          "visibleFeatures": "<Distinctive visual features: label, color, texture>",
          "interactionType": "<How subject interacts: holding, applying, showing, etc.>"
        }
      ],
      "motionDescription": "<Physical movements/gestures: hand movements, product manipulation, body language>",
      "colorPalette": "<3-5 dominant colors in this scene>",
      "energy": "<low | medium | high>",
      "isSwappable": <boolean, true if this scene contains a product that could be replaced>,
      "swapDifficulty": "<easy | medium | hard>",
      "swapNotes": "<Guidance on how to swap the product in this scene. For talking_head: note if product is in hand. For product_shot: note angles and interaction. For broll: note if product-related or generic. Empty string if not swappable.>"
    }
  ],
  "overallStyle": "<2-3 sentences describing the video's overall visual DNA: color grading, production quality, platform feel>",
  "speakerProfile": "<Description of the main speaker: gender, age range, appearance, clothing, energy, speaking style>",
  "productSummary": "<Summary of ALL products detected across all scenes: what they are, how they appear, key visual features>",
  "scriptFull": "<Complete word-for-word transcription of all dialogue>",
  "hookStrategy": "<How the video grabs attention in the first 2-3 seconds>",
  "targetPlatform": "<TikTok | Instagram | YouTube Shorts | general>"
}

SCENE CLASSIFICATION RULES:
- "talking_head": Person speaking directly to camera. May or may not have product in hand.
- "broll": Cutaway footage — close-ups of products, lifestyle shots, environment shots, demonstrations without direct speech to camera.
- "product_shot": Dedicated close-up of the product — unboxing, demo, texture shot, pouring, applying. The product is the STAR of this scene.
- "transition": Motion graphics, text cards, wipes, black frames, or other non-content transitions.

PRODUCT SWAP ANALYSIS:
For EACH scene, analyze whether the product could be swapped:
- isSwappable = true if a competing product is visible and could be replaced with the user's product
- swapDifficulty:
  - "easy" = product is on a surface/stationary, minimal interaction
  - "medium" = product is held in hand or being shown
  - "hard" = product is being actively used (applied, poured, consumed) with complex motion
- swapNotes = specific instructions for regenerating this scene with a different product

TIMESTAMP PRECISION:
- Timestamps must be precise to 0.5 seconds
- Every second of the video must be covered by exactly one scene (no gaps, no overlaps)
- Minimum scene duration: 1 second
- If unsure about a boundary, err on the side of longer scenes rather than splitting too finely

OUTPUT: Return ONLY the JSON object. No markdown code fences. No explanation text.`;

// ─────────────────────────────────────────────
// Download helper
// ─────────────────────────────────────────────

async function downloadToTemp(videoUrl: string): Promise<string> {
  const tempPath = path.join(
    "/tmp",
    `scene_${Date.now()}_${Math.random().toString(36).slice(2)}.mp4`
  );

  const response = await fetch(videoUrl);
  if (!response.ok) {
    throw new Error(`Failed to download video: ${response.status} ${response.statusText}`);
  }

  const buffer = Buffer.from(await response.arrayBuffer());
  fs.writeFileSync(tempPath, buffer);

  console.log(
    `[SceneAnalyzer] Downloaded video: ${(buffer.length / 1024 / 1024).toFixed(1)}MB → ${tempPath}`
  );
  return tempPath;
}

// ─────────────────────────────────────────────
// Main export
// ─────────────────────────────────────────────

/**
 * Analyze a video and segment it into individual scenes with timestamps,
 * types, descriptions, product detection, and swap guidance.
 *
 * Uses Gemini 2.5 Flash's video understanding capabilities to produce
 * a structured JSON breakdown of every scene in the video.
 */
export async function analyzeVideoScenes(videoUrl: string): Promise<SceneAnalysisResult> {
  let tempPath: string | null = null;

  try {
    const geminiKey = await getGeminiKey();
    const ai = new GoogleGenAI({ apiKey: geminiKey });

    // Resolve social media URLs to direct download links
    const resolvedUrl = await resolveVideoUrl(videoUrl);

    // Download video to temp file
    tempPath = await downloadToTemp(resolvedUrl);

    // Upload to Gemini Files API
    console.log("[SceneAnalyzer] Uploading video to Gemini Files API...");
    const uploadResult = await ai.files.upload({
      file: tempPath,
      config: { mimeType: "video/mp4" },
    });

    if (!uploadResult.name) {
      throw new Error("Gemini file upload returned no file name");
    }

    console.log(
      `[SceneAnalyzer] File uploaded: ${uploadResult.name}, state: ${uploadResult.state}`
    );

    // Poll until ACTIVE
    let file = uploadResult;
    let pollAttempts = 0;
    const maxPollAttempts = 60;

    while (file.state === "PROCESSING" && pollAttempts < maxPollAttempts) {
      await new Promise((r) => setTimeout(r, 5000));
      pollAttempts++;
      file = await ai.files.get({ name: file.name! });
      if (pollAttempts % 5 === 0) {
        console.log(`[SceneAnalyzer] Poll ${pollAttempts}: state=${file.state}`);
      }
    }

    if (file.state !== "ACTIVE") {
      throw new Error(`Gemini file processing failed: state=${file.state}`);
    }

    // Analyze with Gemini 2.5 Flash (JSON response mode forces valid JSON output)
    console.log("[SceneAnalyzer] Sending to Gemini 2.5 Flash for scene segmentation...");
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [
            {
              fileData: {
                fileUri: file.uri!,
                mimeType: "video/mp4",
              },
            },
            { text: SCENE_ANALYSIS_PROMPT },
          ],
        },
      ],
      config: {
        responseMimeType: "application/json",
      },
    });

    const rawText = response.text?.trim();

    if (!rawText) {
      throw new Error("Gemini returned empty scene analysis");
    }

    console.log(`[SceneAnalyzer] Raw response: ${rawText.length} chars`);

    // Parse JSON from Gemini response (handles code fences, trailing commas, etc.)
    let parsed: SceneAnalysisResult;
    try {
      parsed = parseLlmJson<SceneAnalysisResult>(rawText);
    } catch (parseErr: any) {
      console.error(`[SceneAnalyzer] Raw Gemini response (first 500 chars): ${rawText.substring(0, 500)}`);
      throw new Error(`Failed to parse scene analysis JSON: ${parseErr.message}`);
    }

    // Validate and sanitize the result
    if (!parsed.scenes || !Array.isArray(parsed.scenes)) {
      throw new Error("Scene analysis missing scenes array");
    }

    // Ensure indices are sequential
    parsed.scenes.forEach((scene, i) => {
      scene.index = i;
    });

    parsed.sceneCount = parsed.scenes.length;

    // Attach the resolved URL so callers can reuse it without re-resolving
    parsed.resolvedVideoUrl = resolvedUrl;

    console.log(
      `[SceneAnalyzer] Analysis complete: ${parsed.sceneCount} scenes, ` +
        `${parsed.totalDuration}s total, ${parsed.aspectRatio}`
    );

    // Log scene breakdown
    for (const scene of parsed.scenes) {
      const productCount = scene.products?.length || 0;
      console.log(
        `[SceneAnalyzer]   Scene ${scene.index}: ${scene.type} (${scene.startSeconds}s-${scene.endSeconds}s, ${scene.durationSeconds}s)` +
          ` products=${productCount} swappable=${scene.isSwappable}`
      );
    }

    // Clean up Gemini file
    try {
      await ai.files.delete({ name: file.name! });
    } catch {
      // Non-fatal
    }

    return parsed;
  } catch (error: any) {
    console.error(`[SceneAnalyzer] Failed to analyze video scenes: ${error.message}`);
    throw error;
  } finally {
    if (tempPath) {
      try {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      } catch {
        // Non-fatal
      }
    }
  }
}

/**
 * Extract just the scenes that contain products (for swap targeting).
 */
export function getSwappableScenes(analysis: SceneAnalysisResult): SceneSegment[] {
  return analysis.scenes.filter((s) => s.isSwappable);
}

/**
 * Extract talking head scenes (for avatar replacement via Kling MC + Sync.so).
 */
export function getTalkingHeadScenes(analysis: SceneAnalysisResult): SceneSegment[] {
  return analysis.scenes.filter((s) => s.type === "talking_head");
}

/**
 * Extract B-roll scenes (for replacement with user's product footage).
 */
export function getBRollScenes(analysis: SceneAnalysisResult): SceneSegment[] {
  return analysis.scenes.filter((s) => s.type === "broll");
}

/**
 * Extract product shot scenes (highest priority for product swap).
 */
export function getProductShotScenes(analysis: SceneAnalysisResult): SceneSegment[] {
  return analysis.scenes.filter((s) => s.type === "product_shot");
}
